language: R
sudo: required
warnings_are_errors: true

branches:
  only:
    - master
    - ci

### For Linux
os:
  - linux

env:
  global:
    - CRAN: https://cran.rstudio.com
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
  - sudo apt-get update -q
  - sudo apt-get install r-cran-rstan
  - sudo apt-get install r-cran-dplyr
  - sudo apt-get install r-cran-ggplot2
  - sudo apt-get install r-cran-knitr
  - sudo apt-get install r-cran-rmarkdown
  - sudo apt-get install r-cran-randomForest
  - sudo apt-get install r-cran-cowplot

r_packages:

r_check_args: --as-cran

notifications:
  email:
    on_success: no
    on_failure: no

